name: hardvard_art
description: Harvard Museum Data Visualization Project
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.1
  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  json_annotation: ^4.8.1
  logging: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.1
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
